name: Reusable Build and Deploy Workflow

on:
  workflow_call:
    inputs:
      app_language:
        description: 'Programming language (python or nodejs)'
        required: false
        default: 'python'
        type: string
      # python_version:
      #   description: 'Python version'
      #   required: false
      #   default: '3.10'
      #   type: string
      # node_version:
      #   description: 'Node.js version'
      #   required: false
      #   default: '18'
      #  type: string
      # app_entry_file:
      #   description: 'Application entry file (Python: app.py, Node.js: app.js)'
      #   required: false
      #   default: 'app.py'
      #   type: string
      # test_file:
      #   description: 'Unit test file name'
      #   required: false
      #   default: 'test_app.py'
      #   type: string
      # test_pattern:
      #   description: 'Test file pattern (Python)'
      #   required: false
      #   default: 'test_*.py'
      #   type: string
      # test_command:
      #   description: 'Test command (Node.js)'
      #   required: false
      #   default: 'npm test'
      #   type: string
      # coverage_threshold:
      #   description: 'Code coverage threshold'
      #   required: false
      #   default: '80'
      #   type: string
      docker_image_name:
        description: 'Docker image name'
        required: false
        default: 'pavan095/github_action_docker'
        type: string
      docker_image_tag:
        description: 'Docker image tag'
        required: false
        default: '1.0.0'
        type: string
      # healthcheck_url:
      #   description: 'Health check URL'
      #   required: false
      #   default: 'http://34.228.255.233:50000'
      #   type: string
      # build_docker:
      #   description: 'Build and push Docker image'
      #   required: false
      #   default: true
      #   type: boolean
      # run_health_check:
      #   description: 'Run health check after deployment'
      #   required: false
      #   default: false
      #   type: boolean
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

env:
  APP_LANGUAGE: ${{ inputs.app_language }}
  # PYTHON_VERSION: ${{ inputs.python_version }}
  # NODE_VERSION: ${{ inputs.node_version }}
  # APP_ENTRY_FILE: ${{ inputs.app_entry_file }}
  # TEST_FILE: ${{ inputs.test_file }}
  # TEST_PATTERN: ${{ inputs.test_pattern }}
  # TEST_COMMAND: ${{ inputs.test_command }}
  # COVERAGE_THRESHOLD: ${{ inputs.coverage_threshold }}
  DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
  DOCKER_IMAGE_TAG: ${{ inputs.docker_image_tag }}
  # HEALTHCHECK_URL: ${{ inputs.healthcheck_url }}

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Python Setup
      - name: Set up Python
        if: ${{ env.APP_LANGUAGE == 'python' }}
        uses: actions/setup-python@v4
        # with:
        #   python-version: ${{ env.PYTHON_VERSION }}

      # Node.js Setup
      - name: Set up Node.js
        if: ${{ env.APP_LANGUAGE == 'nodejs' }}
        uses: actions/setup-node@v4
        # with:
        #   node-version: ${{ env.NODE_VERSION }}

      # Install Dependencies - Python
      - name: Install Python Dependencies
        if: ${{ env.APP_LANGUAGE == 'python' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      # Install Dependencies - Node.js
      - name: Install Node.js Dependencies
        if: ${{ env.APP_LANGUAGE == 'nodejs' }}
        run: npm install

      - name: Generate SBOM for source
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-source.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-source
          path: sbom-source.spdx.json

      # Run Tests - Python Unit Tests
      - name: Run Python Unit Tests with Coverage
        if: ${{ env.APP_LANGUAGE == 'python' }}
        run: |
          coverage run -m unittest test_app.py
          coverage report -m --fail-under=80

      # Run Tests - Python Integration Tests
      - name: Run Python Integration Tests with Coverage
        if: ${{ env.APP_LANGUAGE == 'python' }}
        run: |
          coverage run -a -m unittest discover -s . -p "test_*.py" -v
          coverage report -m --fail-under=80

      # Run  unit Tests - Node.js
      - name: Run Node.js Tests
        if: ${{ env.APP_LANGUAGE == 'nodejs' }}
        run: npm test -- --coverage --fail-on-coverage-threshold=80

      # Run  integration Tests - Node.js
      - name: Run Node.js Tests
        if: ${{ env.APP_LANGUAGE == 'nodejs' }}
        run: npm run test:integration -- --coverage --fail-on-coverage-threshold=80

      # Upload Coverage Report - Python
      - name: Upload Coverage Report
        if: ${{ env.APP_LANGUAGE == 'python' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
      
      - name: Generate Coverage HTML Report
        if: ${{ env.APP_LANGUAGE == 'python' }}
        run: |
          coverage html
          coverage xml

      - name: Upload Coverage Report
        if: ${{ env.APP_LANGUAGE == 'python' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
    - name: Build Docker Image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
   
    - name: Push Docker Image
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Generate SBOM with Syft
      uses: anchore/sbom-action@v0
      with:
        image: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        format: spdx-json
        output-file: sbom.spdx.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.spdx.json

    - name: Run Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy Results to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Install cosign
      uses: sigstore/cosign-installer@v3

    - name: Clear sigstore cache
      run: rm -rf ~/.sigstore ~/.cache/sigstore

    - name: Sign Docker Image
      env:
        COSIGN_EXPERIMENTAL: 1
        SIGSTORE_NO_CACHE: "true"
      run: |
        cosign sign --yes ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Push Signed Image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
      
    - name: Log out from Docker Hub  
      run: docker logout


